### PR TITLE
FeatureAdded:HandleRats

### LINKED ISSUE #10: Write handle_rats() function
If user has bread with them, the rats will attack the user.
The user looses 30 points. 
Return None if no rats

### PR DESCRIPTION
**Pull request by amanamitabh**
closes #10

### CODE REVIEW

**Review by adigulalkari — CHANGES_REQUESTED** [review]
If there is a trap in the room return a string. Please add a return statement in your if statement

**Review by adigulalkari — CHANGES_REQUESTED** [review]
In go to fuc, the handle_rats returns a string. If it is none then give the description. If not give the string returned by handle_rats

**Comment by amanamitabh** [comment]
now returns a string if rats in room and bread in inventory. 
also edited the goto function according to handle rats return statement.

**Review by adigulalkari — COMMENTED** [review]
Okay gtg

**Pull request merged**
