### PR TITLE
updateFunction is added

### LINKED ISSUE #19: Write the update() function
Write the update function, if the player already exists in the file then update the higher score ,else add a new row to the end of the file with name and score as columns.

### PR DESCRIPTION
**Pull request by wrizzzlerrr**
resolve #19

### CODE REVIEW

**Review by adigulalkari — CHANGES_REQUESTED** [review]
Not necesasry to change the go_to function. The update looks good. Remove go_to then ill merge update

**Comment by wrizzzlerrr** [comment]
> Not necesasry to change the go_to function. The update looks good. Remove go_to then ill merge update

bhaiya im unable to change it thats why i have added both of them together

**Comment by adigulalkari** [comment]
whats the issue?

**Comment by adigulalkari** [comment]
Its alright. good job.

**Pull request merged**
